### ISSUE TITLE
Ruby 2.0 problem coming from pbkdf2

### ISSUE THREAD

**Issue by mulderp** [antirez/lamernews#145]
Currently, there is a problem when running a Ruby 2.0 environment:

<pre>
2013-08-09T08:56:14.166458+00:00 app[web.1]: 82.135.122.35 - - [09/Aug/2013 08:56:14] "GET /api/login?username=.....&password=..... HTTP/1.1" 200 79 0.0051
2013-08-09T08:56:18.663483+00:00 app[web.1]: TypeError - nil can't be coerced into Fixnum:
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:145:in `each_with_index'
2013-08-09T08:56:18.663483+00:00 app[web.1]:    /app/pbkdf2.rb:146:in `^'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:146:in `block in xor_impl'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:145:in `each'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:119:in `block in calculate_block'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:190:in `^'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:115:in `upto'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:115:in `calculate_block'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:145:in `xor_impl'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/pbkdf2.rb:77:in `value'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/pbkdf2.rb:131:in `calculate!'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/app.rb:917:in `create_user'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/app.rb:460:in `block in '
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:131:in `upto'
2013-08-09T08:56:18.663661+00:00 app[web.1]:    /app/pbkdf2.rb:132:in `block in calculate!'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.2/lib/sinatra/base.rb:944:in `block (3 levels) in route!'
2013-08-09T08:56:18.663836+00:00 app[web.1]:    /app/pbkdf2.rb:84:in `hex_string'
2013-08-09T08:56:18.663979+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.2/
</pre>

**Comment by fcambus** [comment]
It's been a long time, but just merged #161 which fixes the issue. Thanks to everyone involved in this thread.
