### ISSUE TITLE
Internal Server Error when deploying to Heroku

### ISSUE THREAD

**Issue by danielflopes** [antirez/lamernews#156]
Hi,

I've deployed Lamer News to Heroku using these instructions: 
https://github.com/antirez/lamernews/wiki/Deployment

Anyhow, I receive this message when accessing the app via browser.
"Internal Server Error"

Can you tell me where the problem is?

Last lines of Heroku log:

<code>
2014-02-11T16:41:00.757351+00:00 app[web.1]: 	/app/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
2014-02-11T16:41:00.757351+00:00 app[web.1]: 	/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
2014-02-11T16:41:00.760162+00:00 app[web.1]: 188.81.72.69 - - [11/Feb/2014 16:41:00] "GET / HTTP/1.1" 500 30 0.0058
2014-02-11T16:41:01.551577+00:00 app[web.1]: 188.81.72.69 - - [11/Feb/2014 16:41:01] "GET /favicon.ico HTTP/1.1" 200 414 0.0006
2014-02-11T16:41:08.022164+00:00 heroku[web.1]: Stopping remaining processes with SIGKILL
2014-02-11T16:41:08.021801+00:00 heroku[web.1]: Error R12 (Exit timeout) -> At least one process failed to exit within 10 seconds of SIGTERM
2014-02-11T16:41:10.044530+00:00 heroku[web.1]: Process exited with status 137'
</code>

**Comment by fcambus** [comment]
Closing this as it's likely a configuration issue not related to the project.
